# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode11.2
language: objective-c
xcode_project: Example/DragRotateScaleView.xcworkspace
xcode_scheme: DragRotateScaleView-Example
xcode_sdk: iphonesimulator13.2
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
- pod lib lint
